"""engine — the registry-driven copy-trading orchestrator for mimiq2."""

class WalletSpec:
    ...

class SourceHub:

    def __init__(self, spec: DEXSpec, trader_id: str, market_map: Dict[int, str], notify_fn: Optional[Callable]=...):
        ...

    def start(self) -> None:
        ...

    def trader_active_recently(self, coin: str, window_s: float) -> bool:
        ...

    async def stop(self) -> None:
        ...

    def n_followers(self) -> int:
        ...

    def ready(self) -> bool:
        ...

    def trader_positions(self) -> Dict[str, float]:
        ...

    def executors(self) -> List[BaseExecutor]:
        ...

    async def attach(self, ex: BaseExecutor) -> None:
        ...

    def detach(self, wallet_id: int) -> None:
        ...

class CopyEngine:

    def __init__(self, transport_provider: TransportProvider, market_map_provider: MarketMapProvider, notify_provider: Optional[NotifyProvider]=..., on_key_status: Optional[Callable[[int, bool], Awaitable[None]]]=..., market_refresh: Optional[Callable[[], Awaitable[str]]]=..., watch_notify: Optional[Callable[[int, str], Awaitable[None]]]=..., on_wallet_removed: Optional[Callable[[int], None]]=..., shard_id: int=..., shard_count: int=...):
        ...

    def wake_resync(self) -> None:
        ...

    def wake_web_actions(self) -> None:
        ...

    async def add_wallet(self, ws: WalletSpec) -> None:
        ...

    async def remove_wallet(self, wallet_id: int) -> None:
        ...

    async def sync_wallets(self, wallets: List[WalletSpec]) -> None:
        ...

    async def sync_watch_subscriptions(self) -> None:
        ...

    async def run_reconcile_loop(self) -> None:
        ...

    async def run_market_map_refresh_loop(self) -> None:
        ...

    async def run_own_pos_poll_loop(self) -> None:
        ...

    async def run_api_key_check_loop(self) -> None:
        ...

    async def run_resync_loop(self, snapshot: Callable[[], Awaitable[List[WalletSpec]]]) -> None:
        ...

    async def run_web_action_loop(self, transport_provider) -> None:
        ...

    async def stop(self) -> None:
        ...
