"""dn.pair_executor — open / close / guard a two-leg delta-neutral pair."""

class Leg:

    def tokens(self) -> float:
        ...

async def size_legs(long: Leg, short: Leg, size_tokens: float) -> Tuple[bool, str]:
    ...

async def open_pair(long: Leg, short: Leg, lmark: Optional[float]=..., smark: Optional[float]=..., l_fix: Optional[float]=..., s_fix: Optional[float]=..., mode: str=..., expected_long_pos: Optional[float]=..., expected_short_pos: Optional[float]=...) -> Tuple[bool, float, float, str]:
    ...

async def estimate_close_cost_usd(long: Leg, short: Leg) -> Optional[float]:
    ...

async def estimate_close_exit_prices(long: Leg, short: Leg) -> Optional[Tuple[float, float]]:
    ...

async def close_pair(long: Leg, short: Leg) -> Tuple[bool, str]:
    ...

async def open_pair_patient(long: Leg, short: Leg, patience_s: float) -> Tuple[bool, float, float, str, dict]:
    ...

async def close_pair_patient(long: Leg, short: Leg, patience_s: float) -> Tuple[bool, str, dict]:
    ...

def leg_trigger_price(entry: float, contracts: float, is_long_leg: bool, kind: str, value: float, vtype: str) -> float:
    ...

def leg_stop_capable(leg: Leg) -> bool:
    ...

async def arm_leg_stops(long: Leg, short: Leg, pair: dict) -> Tuple[bool, str]:
    ...

async def remove_leg_stops(long: Leg, short: Leg) -> None:
    ...

async def close_report(long: Leg, short: Leg, since_ts: float) -> Optional[dict]:
    ...

def pair_pnl(pair: dict, mark_long: float, mark_short: float) -> float:
    ...

async def check_pair(long: Leg, short: Leg, l_ceiling: Optional[float]=..., s_ceiling: Optional[float]=...) -> Tuple[str, str]:
    ...

async def true_up_pair(long: Leg, short: Leg, never_top_up: bool=...) -> Tuple[bool, str]:
    ...

async def reduce_leg_excess(leg: Leg, is_long: bool, target_contracts: float) -> Tuple[bool, str]:
    ...

async def flatten_leg(leg: Leg, is_long: bool) -> Tuple[bool, str]:
    ...
